# \u5F3A\u5236 DevTools \u5C06 LangChain4j \u76F8\u5173\u5E93\u52A0\u5165 RestartClassLoader
restart.include.langchain4j=/langchain4j-.*\.jar
restart.include.dashscope=/dashscope-sdk-java-.*\.jar
restart.include.okhttp=/okhttp-.*\.jar